#!/bin/bash

# TO RUN: 
#   sbatch -N4 -n4 -p opteron -x c[53,101,102] run_tests

# RUN V2 TESTS

make -f p3.Makefile lake

prun ./lake 16 5 1.0
prun ./lake 32 5 1.0
prun ./lake 64 5 1.0
prun ./lake 128 5 1.0
prun ./lake 256 5 1.0
prun ./lake 512 5 1.0
prun ./lake 1024 5 1.0

prun ./lake 16 5 1.0 8
prun ./lake 32 5 1.0 8
prun ./lake 64 5 1.0 8
prun ./lake 128 5 1.0 8
prun ./lake 256 5 1.0 8
prun ./lake 512 5 1.0 8
prun ./lake 1024 5 1.0 8
prun ./lake 2048 5 1.0 8
prun ./lake 2048 5 1.0 16
prun ./lake 2048 5 1.0 32

make -f p3.Makefile clean

# RUN V4 TESTS

make -f p3.Makefile lake-mpi

prun ./lake 16 5 1.0 8
prun ./lake 32 5 1.0 8
prun ./lake 64 5 1.0 8
prun ./lake 128 5 1.0 8
prun ./lake 256 5 1.0 8
prun ./lake 512 5 1.0 8
prun ./lake 1024 5 1.0 8
prun ./lake 2048 5 1.0 8
prun ./lake 2048 5 1.0 16
prun ./lake 2048 5 1.0 32

gnuplot heatmap.gnu

make -f p3.Makefile clean

exit