#!/bin/bash

####################################################################################
# FILE:         setup_p3
#
# AUTHORS:      attiffan    Aurora T. Tiffany-Davis
#
# DESCRIPTION:  A script to aid in testing for HW04, Problem 3
#               Here we are picking 3 power-connected nodes (21,22,24)
#               We will be doing power monitoring on 21
#                   USB power meter
#               We will be running Lulesh on 22
#                   available frequency steps:
#                   2.00 GHz, 1.50 GHz, 1.20 GHz, 1000 MHz, 800 MHz
#
# TO RUN:       Open 2 ARC Terminal Windows
#                   On FIRST Window
#                       Reserve Nodes
#                           srun -N 3 -n 8 -popteron -w c[21,22,24] --pty /bin/bash
#                           [now you are on c21]
#                   On SECOND Window
#                       SSH to Lulesh node
#                           ssh c22
#                           [now you are on c22]
#                       Run this Script
#                           source setup_p3 [0-4 frequency step index]
#                   On FIRST Window
#                       Start Power Monitoring
#                           wattsup ttyUSB0 watts
#                   On SECOND Window
#                       Run the Other Script
#                           ./run_p3
#                   On FIRST Window
#                       Stop Power Monitoring
#                           Ctrl+C
####################################################################################

# Set Frequency Variable
if [ $1 == "0" ]; then
    FREQ="2.00GHz"
elif [ $1 == "1" ]; then
    FREQ="1.50GHz"
elif [ $1 == "2" ]; then
    FREQ="1.20GHz"
elif [ $1 == "3" ]; then
    FREQ="1000MHz"
elif [ $1 == "4" ]; then
    FREQ="800MHz"
fi

# Load PAPI
module load papi

# Compile
make MPI_OPENMP

# Set CPU Frequency
sudo cpupower frequency-set -g userspace
sudo cpupower frequency-set -f $FREQ

# Print CPU Frequency for warm fuzzy feeling
cpupower frequency-info

# Set Number of Threads
export OMP_NUM_THREADS=8

